language: php
php:
  - 5.6
  - 7.0
  - 7.1

script:
  # Check php script syntax
  - bash .travis.phplint.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#testadminwiki"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
